import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@nous-research/ui/ui/components/card";
import { useI18n } from "@/i18n";

/**
 * Artifacts — interactive HTML dashboards, Excalidraw diagrams, and other
 * generated artifacts will appear here (M12/M13 roadmap).
 */
export default function ArtifactsPage() {
  const { t } = useI18n();
  const a = t.artifacts;

  return (
    <div className="container mx-auto max-w-4xl space-y-6 py-8">
      <div>
        <h1 className="text-2xl font-semibold">{a?.title ?? "Artifacts"}</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          {a?.subtitle ?? "Interactive HTML dashboards and diagrams generated by your projects."}
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>{a?.emptyTitle ?? "No artifacts yet"}</CardTitle>
          <CardDescription>
            {a?.emptyDescription ?? "Artifacts will appear here as they are generated."}
          </CardDescription>
        </CardHeader>
        <CardContent className="flex min-h-[240px] items-center justify-center rounded-md border border-dashed text-sm text-muted-foreground">
          <div className="flex flex-col items-center gap-2">
            <span className="text-3xl">📊</span>
            <span>
              {a?.emptyHint ?? "Interactive HTML dashboards and Excalidraw diagrams will appear here."}
            </span>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
